#!/usr/bin/env python3
"""
regenerate_derived_files.py

Regenerates all derived files from the authoritative sources:
  1. task_names.json         — flat alphabetical name-view of tasks
  2. process_task_index.json — process-to-task reverse index (thin)
  3. process_task_crossref.md — task-centric process links
  4. file_inventory.md       — human-readable file inventory

Sources:
  task_details.json    — authoritative task records
  process_details.json — authoritative process/category catalog
  file_inventory.json  — authoritative file inventory

NOTE: process_reference.md and process_categories.md were archived to
original_3/ on 2026-04-19. process_details.json is now authoritative
for all process and category content. This script does NOT modify
process_details.json.
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent.parent

TASK_DETAILS     = REPO_ROOT / "task_details.json"
PROCESS_DETAILS  = REPO_ROOT / "process_details.json"
FILE_INVENTORY   = REPO_ROOT / "file_inventory.json"

OUT_TASK_NAMES    = REPO_ROOT / "task_names.json"
OUT_PROCESS_INDEX = REPO_ROOT / "process_task_index.json"
OUT_CROSSREF      = REPO_ROOT / "process_task_crossref.md"
OUT_INVENTORY_MD  = REPO_ROOT / "file_inventory.md"


def load_tasks():
    return json.loads(TASK_DETAILS.read_text(encoding="utf-8"))


def load_process_vocabulary():
    """Load process_id → process_name mapping from process_details.json."""
    data = json.loads(PROCESS_DETAILS.read_text(encoding="utf-8"))
    return {p["process_id"]: p["process_name"] for p in data["processes"]}


def load_inventory():
    return json.loads(FILE_INVENTORY.read_text(encoding="utf-8"))


# ---- task_names.json ----

def generate_task_names(tasks):
    entries = []
    for t in tasks:
        entries.append({
            "hedtsk_id": t["hedtsk_id"],
            "canonical_name": t["canonical_name"],
            "short_definition": t.get("short_definition", ""),
            "aliases": t.get("aliases", []),
            "variation_names": [v["name"] for v in t.get("variations", [])],
        })
    entries.sort(key=lambda e: e["canonical_name"])
    return {
        "description": (
            "DERIVED FILE. Regenerated by outputs/regenerate_derived_files.py "
            "from task_details.json. Do not edit by hand — edit task_details.json "
            "and regenerate."
        ),
        "total_tasks": len(entries),
        "tasks": entries,
    }


# ---- process_task_index.json (thin reverse-index) ----

def generate_process_task_index(tasks, process_vocab):
    reverse = {}
    for t in tasks:
        for pid in t.get("hed_process_ids", []):
            if pid not in reverse:
                reverse[pid] = []
            reverse[pid].append({
                "hedtsk_id": t["hedtsk_id"],
                "canonical_name": t["canonical_name"],
            })

    processes = []
    for pid in sorted(reverse.keys()):
        name = process_vocab.get(pid, pid.replace("hed_", "").replace("_", " ").capitalize())
        tasks_list = sorted(reverse[pid], key=lambda x: x["canonical_name"])
        processes.append({
            "process_id": pid,
            "process_name": name,
            "tasks": tasks_list,
            "task_count": len(tasks_list),
        })

    return {
        "description": (
            "DERIVED FILE (thin reverse-index). Regenerated by "
            "outputs/regenerate_derived_files.py from task_details.json "
            "(authoritative task records) and process_details.json "
            "(authoritative process vocabulary). Do not edit by hand — "
            "edit the sources and regenerate. "
            "NOTE: This is NOT the authoritative process_details.json. "
            "See process_details.json for the enriched catalog with "
            "categories, definitions, citations, and notes."
        ),
        "total_processes": len(processes),
        "total_tasks": len(tasks),
        "processes": processes,
    }


# ---- process_task_crossref.md ----

def generate_crossref(tasks, process_vocab):
    lines = [
        "# Process–Task Cross-Reference",
        "",
        "**Purpose:** For each task, lists its linked process IDs with human-readable names.",
        "",
        "DERIVED FILE. Regenerated by `outputs/regenerate_derived_files.py` from "
        "`task_details.json` and `process_details.json`. Do not edit by hand.",
        "",
        "---",
        "",
    ]
    for t in sorted(tasks, key=lambda t: t["canonical_name"]):
        tid = t["hedtsk_id"]
        name = t["canonical_name"]
        pids = t.get("hed_process_ids", [])
        lines.append(f"### `{tid}` — {name}")
        lines.append("")
        if pids:
            for pid in pids:
                pname = process_vocab.get(pid, pid)
                lines.append(f"- `{pid}` ({pname})")
        else:
            lines.append("- *(no processes linked)*")
        lines.append("")
    return "\n".join(lines) + "\n"


# ---- file_inventory.md ----

def generate_file_inventory_md(inventory):
    """Generate file_inventory.md from the file_inventory.json data structure."""
    lines = [
        "# File Inventory — HED Task Catalog",
        "",
        f"**Updated:** {inventory['updated']}  ",
        "**Purpose:** Map of all files in the Claude-research project, "
        "their roles, and their current status.",
        "",
        "DERIVED FILE. Regenerated by `outputs/regenerate_derived_files.py` "
        "from `file_inventory.json`. "
        "Do not edit by hand — edit `file_inventory.json` and regenerate.",
        "",
        "---",
        "",
    ]

    for section in inventory["sections"]:
        lines.append(f"## {section['title']}")
        lines.append("")
        if section.get("intro"):
            lines.append(section["intro"])
            lines.append("")

        files = section.get("files", [])
        file_entries = [f for f in files if f.get("type") != "directory"]
        dir_entries  = [f for f in files if f.get("type") == "directory"]

        if file_entries:
            lines.append("| File | Description | Status |")
            lines.append("|------|-------------|--------|")
            for f in file_entries:
                path = f"`{f['path']}`"
                desc = f["description"].replace("|", "\\|")
                status = f.get("status", "")
                # For derived files, append generator note to description
                gen = f.get("generated_by")
                if gen:
                    sources = ", ".join(f"`{s}`" for s in f.get("generated_from", []))
                    desc = f"{desc} *(generated from {sources})*"
                lines.append(f"| {path} | {desc} | {status} |")
            lines.append("")

        if dir_entries:
            for d in dir_entries:
                lines.append(f"- **`{d['path']}`** — {d['description']}")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


# ---- main ----

def main():
    tasks = load_tasks()
    process_vocab = load_process_vocabulary()
    inventory = load_inventory()

    print(f"Loaded {len(tasks)} tasks, {len(process_vocab)} process vocabulary entries")

    # 1. task_names.json
    tn = generate_task_names(tasks)
    OUT_TASK_NAMES.write_text(
        json.dumps(tn, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_TASK_NAMES.name}: {tn['total_tasks']} tasks")

    # 2. process_task_index.json
    pi = generate_process_task_index(tasks, process_vocab)
    OUT_PROCESS_INDEX.write_text(
        json.dumps(pi, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_PROCESS_INDEX.name}: {pi['total_processes']} processes, {pi['total_tasks']} tasks")

    # 3. process_task_crossref.md
    xref = generate_crossref(tasks, process_vocab)
    OUT_CROSSREF.write_text(xref, encoding="utf-8")
    xref_count = xref.count("### `hedtsk_")
    print(f"Wrote {OUT_CROSSREF.name}: {xref_count} task entries")

    # 4. file_inventory.md
    inv_md = generate_file_inventory_md(inventory)
    OUT_INVENTORY_MD.write_text(inv_md, encoding="utf-8")
    section_count = inv_md.count("\n## ")
    print(f"Wrote {OUT_INVENTORY_MD.name}: {section_count} sections")


if __name__ == "__main__":
    main()
