#!/usr/bin/env python3
"""
regenerate_derived_files.py

Regenerates all derived files from the authoritative task_details.json:
  1. task_names.json — flat alphabetical name-view projection
  2. process_task_index.json — process-to-task reverse index (thin, derived)
  3. process_task_crossref.md — task-centric process links

Also reads process_reference.md for the process vocabulary (IDs and names).

NOTE: process_details.json is now AUTHORITATIVE (enriched with categories,
definitions, citations, and notes — produced by run_extraction.py).
This script does NOT touch process_details.json. The thin reverse-index
it produces is a separate convenience file: process_task_index.json.
"""

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent

TASK_DETAILS = REPO_ROOT / "task_details.json"
PROCESS_REF = REPO_ROOT / "process_reference.md"
OUT_TASK_NAMES = REPO_ROOT / "task_names.json"
OUT_PROCESS_INDEX = REPO_ROOT / "process_task_index.json"
OUT_CROSSREF = REPO_ROOT / "process_task_crossref.md"


def load_tasks():
    return json.loads(TASK_DETAILS.read_text(encoding="utf-8"))


def load_process_vocabulary():
    """Parse process_reference.md for process_id → process_name mapping."""
    vocab = {}
    HEAD3_RE = re.compile(r"^### (.+?)\s+`([a-z0-9_]+)`")
    for line in PROCESS_REF.read_text(encoding="utf-8").splitlines():
        m = HEAD3_RE.match(line)
        if m:
            name = m.group(1).strip()
            pid = m.group(2).strip()
            vocab[pid] = name
    return vocab


# ---- task_names.json ----

def generate_task_names(tasks):
    entries = []
    for t in tasks:
        entries.append({
            "hedtsk_id": t["hedtsk_id"],
            "canonical_name": t["canonical_name"],
            "short_definition": t.get("short_definition", ""),
            "aliases": t.get("aliases", []),
            "variation_names": [v["name"] for v in t.get("variations", [])],
        })
    # Sort alphabetically by canonical_name
    entries.sort(key=lambda e: e["canonical_name"])
    return {
        "description": (
            "DERIVED FILE. Regenerated by outputs/regenerate_derived_files.py "
            "from task_details.json. Do not edit by hand — edit task_details.json "
            "and regenerate."
        ),
        "total_tasks": len(entries),
        "tasks": entries,
    }


# ---- process_task_index.json (thin reverse-index — NOT the authoritative process_details.json) ----

def generate_process_task_index(tasks, process_vocab):
    # Build reverse index: process_id → list of tasks
    reverse = {}
    for t in tasks:
        for pid in t.get("hed_process_ids", []):
            if pid not in reverse:
                reverse[pid] = []
            reverse[pid].append({
                "hedtsk_id": t["hedtsk_id"],
                "canonical_name": t["canonical_name"],
            })

    # Build process entries, sorted alphabetically by process_id
    processes = []
    for pid in sorted(reverse.keys()):
        name = process_vocab.get(pid, pid.replace("hed_", "").replace("_", " ").capitalize())
        tasks_list = sorted(reverse[pid], key=lambda x: x["canonical_name"])
        processes.append({
            "process_id": pid,
            "process_name": name,
            "tasks": tasks_list,
            "task_count": len(tasks_list),
        })

    return {
        "description": (
            "DERIVED FILE (thin reverse-index). Regenerated by "
            "outputs/regenerate_derived_files.py from task_details.json "
            "(authoritative task records) and process_reference.md "
            "(authoritative process vocabulary). Do not edit by hand — "
            "edit the sources and regenerate. "
            "NOTE: This is NOT the authoritative process_details.json. "
            "See process_details.json for the enriched catalog with "
            "categories, definitions, citations, and notes."
        ),
        "total_processes": len(processes),
        "total_tasks": len(tasks),
        "processes": processes,
    }


# ---- process_task_crossref.md ----

def generate_crossref(tasks, process_vocab):
    lines = [
        "# Process–Task Cross-Reference",
        "",
        "**Purpose:** For each task, lists its linked process IDs with human-readable names.",
        "",
        "DERIVED FILE. Regenerated by `outputs/regenerate_derived_files.py` from "
        "`task_details.json` and `process_reference.md`. Do not edit by hand.",
        "",
        "---",
        "",
    ]
    # Sort tasks alphabetically by canonical_name
    sorted_tasks = sorted(tasks, key=lambda t: t["canonical_name"])
    for t in sorted_tasks:
        tid = t["hedtsk_id"]
        name = t["canonical_name"]
        pids = t.get("hed_process_ids", [])
        lines.append(f"### `{tid}` — {name}")
        lines.append("")
        if pids:
            for pid in pids:
                pname = process_vocab.get(pid, pid)
                lines.append(f"- `{pid}` ({pname})")
        else:
            lines.append("- *(no processes linked)*")
        lines.append("")
    return "\n".join(lines) + "\n"


# ---- main ----

def main():
    tasks = load_tasks()
    process_vocab = load_process_vocabulary()

    print(f"Loaded {len(tasks)} tasks, {len(process_vocab)} process vocabulary entries")

    # 1. task_names.json
    tn = generate_task_names(tasks)
    OUT_TASK_NAMES.write_text(
        json.dumps(tn, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_TASK_NAMES.name}: {tn['total_tasks']} tasks")

    # 2. process_task_index.json (thin reverse-index; NOT process_details.json)
    pi = generate_process_task_index(tasks, process_vocab)
    OUT_PROCESS_INDEX.write_text(
        json.dumps(pi, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT_PROCESS_INDEX.name}: {pi['total_processes']} processes, {pi['total_tasks']} tasks")

    # 3. process_task_crossref.md
    xref = generate_crossref(tasks, process_vocab)
    OUT_CROSSREF.write_text(xref, encoding="utf-8")
    xref_count = xref.count("### `hedtsk_")
    print(f"Wrote {OUT_CROSSREF.name}: {xref_count} task entries")


if __name__ == "__main__":
    main()
